Updated documentation (see description)
OpenShock/Wiki pull request #72
Opened 2024-09-28 05:17 UTC by Soulsender

Added:
- additional information in assembly, including an example diagram of solder connections
- additional safety warnings in places it seemed like a good idea
- additional product links for shockers and transmitters
- added image of transmitter

Changed:
- created a drop down for transmitters, as it is a little unclear that the "Transmitter" section is a clickable area
- moved the warning about not changing the "RF TX Pin" in the web UI farther up in the page to a more relevant spot

2024-10-01 08:30 UTC, hhvrc requested changes

2024-10-01 08:30 UTC, hhvrc commented on docs/guides/openshock-first-setup.md
> +    The electricity will flow through your heart.
I would rather try to warn the user to try to no touch with both hands when its powered on because it *could* send electricity trough the heart.

2024-10-01 08:30 UTC, hhvrc commented on docs/guides/openshock-first-setup.md
> +!!! warning "RF TX Pin" **DO NOT** change the RF TX Pin **UNLESS IT IS NOT AUTOMATICALLY DETECTED**. This is an advanced feature. It should be set correctly by default after flashing the OpenShock fi
There shouldnt be a need to reflash, just change the pin via serial or wifi

2024-10-01 08:30 UTC, hhvrc commented on docs/guides/openshock-first-setup.md
> +!!! warning "RF TX Pin" **DO NOT** change the RF TX Pin **UNLESS IT IS NOT AUTOMATICALLY DETECTED**. This is an advanced feature. It should be set correctly by default after flashing the OpenShock fi
You could just copy the comment you removed below and then explain after how to change the pin I guess

2024-10-01 08:30 UTC, hhvrc commented on docs/hardware/shockers/index.md
> +    The electricity will flow through your heart.
Again here, make it a warning, and that theres a cahnce it could flow trough hear

2024-10-01 08:30 UTC, hhvrc commented on docs/safety/safety-rules.md
> +
Here too

2024-10-01 08:30 UTC, hhvrc commented on docs/guides/openshock-first-setup.md
> -    ??? Info "Images"
Wont this take up more space in the wiki, if we show all images by default?

2024-10-05 23:30 UTC, Soulsender commented
Alright, I've made the requested changes, re-requesting review

2024-10-07 19:03 UTC, hhvrc approved these changes

2024-10-07 19:03 UTC, merged